# tasks/01-common.yml
---
- name: Disable swap
  ansible.builtin.shell: swapoff -a
  args:
    creates: /proc/swaps # Only run if swap is active
  changed_when: true # Always report changed if swapoff is executed

- name: Comment out swap entry in /etc/fstab
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^(\s*)([^#]+\s+swap\s+sw\s+.*)$'
    replace: '#\1\2'
    backup: yes

- name: Load overlay and br_netfilter modules
  community.general.modprobe: # <--- CORRECTED: Removed ansible.builtin.
    name: "{{ item }}"
    state: present
  loop:
    - overlay
    - br_netfilter

- name: Add sysctl settings for Kubernetes networking
  ansible.builtin.template:
    src: 99-k8s-sysctl.conf.j2 # <--- CHANGE THIS LINE
    dest: /etc/sysctl.d/99-kubernetes-sysctl.conf
    owner: root
    group: root
    mode: '0644'

- name: Apply sysctl settings without reboot
  ansible.builtin.command: sysctl --system
  changed_when: true # Always report changed as it's an imperative command

- name: Ensure bridge-nf-call-iptables is enabled
  ansible.builtin.sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: "1"
    state: present
    reload: yes

- name: Disable UFW (Uncomplicated Firewall) for simplicity (production environments should configure rules)
  ansible.builtin.ufw:
    state: disabled
  ignore_errors: true # UFW might not be installed on all Ubuntu versions/cloud images
  when: ansible_facts.distribution == "Ubuntu"

- name: Add Kubernetes DNS domain and host entries to /etc/hosts (for inter-node communication)
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "{{ hostvars[item]['ansible_facts'][api_server_advertise_address_interface]['ipv4']['address'] }} {{ item }}"
    insertafter: EOF
  loop: "{{ groups['kube_nodes'] }}"