apiVersion: v1
kind:  Service
metadata:
   name: result-app-svc
   labels: 
     name: result-app-svc
     app: votingapp
spec: 
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30006
  selector: 
      name: result-app-pod
      app: votingapp
  