---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: vote-app-deploy
  labels: 
    app: votingapp
    name: vote-app-deploy
spec: 
  replicas: 2
  selector:
    matchLabels: 
      app: votingapp
      name: vote-app
  template:
    metadata: 
      labels: 
        app: votingapp
        name: vote-app
    spec: 
      containers: 
        - name: vote-app
          image: kodekloud/examplevotingapp_vote:v1
          ports:
            - containerPort: 80
