apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vote-result-multi-host-ingress 
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: / 
spec:
  rules:
    - host: vote.local 
      http:
        paths:
          - path: 
            pathType: Prefix
            backend:
              service:
                name: vote-app-svc 
                port:
                  number: 80 
    - host: result.local 
      http:
        paths:
          - path: / 
            pathType: Prefix
            backend:
              service:
                name: result-app-svc 
                port:
                  number: 80 # The port on the result-app-svc
